version: "3.8"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app:delegated
      - /app/node_modules
      - ~/Database:/app/Database:rw
      - ./public/uploads:/app/public/uploads:rw
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true